### ISSUE TITLE
Event page/layout

### ISSUE THREAD

**Issue by spencerng** [universitytheater/utheater.github.io#10]
Create a reusable layout for UT events (performances and otherwise) that can be listed vertically on a webpage.

Each event may or may not include the following:
* Date/time
* Location
* Blurb
* Link to FB event or other websites
* Graphic

Events should be readable and use minimal text (i.e. use icons to represent date/location)

**Feature Enhancements**

- [x] Detect if the layout is on a mobile device or if there is no image present, and if so, remove the image column
- [x] Allow events to be generated from a YAML file, removing layout elements as needed if certain parameters (e.g. graphics, links) aren't present
- [x] Create a multi-line vertical division for events with multiple links (i.e. the audition event should have signups and the FB event links on separate lines, but both to the right of the link icon) _[Still needs to be cleaned up]_

**Comment by isaiahzs** [comment]
Self assigning to clean up what's left here

**Comment by isaiahzs** [comment]
> Create a multi-line vertical division for events with multiple links (i.e. the audition event should have signups and the FB event links on separate lines, but both to the right of the link icon) [Still needs to be cleaned up]

For the events with multiple links, display them vertically rather than in a comma separated list
