### ISSUE TITLE
Galleries

### ISSUE THREAD

**Issue by spencerng** [universitytheater/utheater.github.io#12]
Create an adaptable gallery widget (e.g. to show off past shows) that takes in a yaml file with a list of images as an input and displays them in a rotation

**Comment by isaiahzs** [comment]
Are there any shows that have multiple images that I could use to test with?

**Comment by spencerng** [comment]
Yup, the gallery images have now been scraped from the old arts page and
are at `assets/show-slideshow/<slug>`!

**Comment by spencerng** [comment]
Some changes/bugs that need to be fixed (happy to help with them as well!)

- [ ] No gallery if the show just contains a banner
- [ ] Scaling for mobile should use relative units, perhaps with less vertical whitespace? Mobile currently leaves the image cropped
- [ ] White arrows are hard to see

**Comment by isaiahzs** [comment]
Could we steal whatever code the TAPS site uses for galleries and just drop that in? Or is it too ingrained in their mess?

**Comment by spencerng** [comment]
We've managed to hack in these features now on show pages and the homepage, consider it closed :)
