### ISSUE TITLE
Replicate past shows

### ISSUE THREAD

**Issue by spencerng** [universitytheater/utheater.github.io#15]
- [x] Parse https://arts.uchicago.edu/utshows to build a list of all past shows
- [x] Within each show, ensure the following are parameterized into their own fields:
  - [x] Title
  - [x] Quarter/year
  - [ ] Original publishing company
  - [ ] Theater
  - [ ] Dates
  - [ ] Short description
  - [x] Cover image
  - [ ] Thumbnail image
  - [ ] Cast and crew, with name, position, and bio
- [x] Create a page (ut.uchicago.edu/shows) that replicates the UChicago Arts page, separating shows by year
  - [ ] Correct any pronouns/dead names from old bios
  - [ ] Integrate other media found on the internet (e.g. rehearsal photos) by creating a media gallery widget that takes in a source image URL

**Comment by isaiahzs** [comment]
I started this over [here](https://github.com/utheater/taps-utshows-archive). If that stuff looks good to you, I can make a PR to add the info the this site, I just wanted to make sure it's all correct first.

**Comment by isaiahzs** [comment]
This ties in to #21 if we end up removing the dependency and making each show its own page in a collection (with a lot of frontmatter).

**Comment by isaiahzs** [comment]
Unassigning because I don't know what do work on here, or if it's already done.

**Comment by spencerng** [comment]
Aside from parameterizing company member names (which will likely have to be done manually), this is done. #12 still needs a bit of work on show pages though.
